### ISSUE TITLE
Can't login to MySQL without using sudo

### ISSUE THREAD

**Issue by maartenwolfsen** [tdgroot/ansible-workstation-common#59]
System: Fedora Workstation 30

After installing a fresh new Fedora Workstation 30 installation, I executed a playbook, using the tdegroot.workstation-common role. After this, I noticed that I could not login to MySQL on the command line, without using sudo.

**Comment by diedburn** [comment]
### As for fixing the problem:
Are the contents of `~/.my.cnf`  okay?
The contents for the default configuration should look something like:
`[client]
user=root
host=localhost
password=mysql`

If thats okay you could check the file permissions of the file, these should be read/write for the owner only (chmod 700)

### The problem:
I will try to confirm this on my local machine soon

**Comment by tdgroot** [comment]
Fixed in 8590c0c40d16649b0c1f4058c60f00c023e506d8. Please check it out and let me know if the problem still occurs. Closing for now!
