### ISSUE TITLE
Ansible Galaxy platform list is outdated

### ISSUE THREAD

**Issue by diedburn** [tdgroot/ansible-workstation-common#66]
https://galaxy.ansible.com/tdgroot/workstation-common

* Edit:
Anisble Galaxy has not been updated. probably not an issue.

**Comment by tdgroot** [comment]
Well the platforms mentioned in `meta/main.yml` surely are updated (F28 and F29). 

I'll update it shortly, especially with F32 releasing in two weeks.

**Comment by tdgroot** [comment]
@diedburn Over the course of last few months, the role has been updated for compatibility with Fedora 32. I also updated the Ansible Galaxy entry.
